name: main
on: [push]
jobs:
  run:
    name: run
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
    - name: setup-node
      uses: actions/setup-node@master
      with:
        node-version: 12.x
    - name: install
      run: yarn
    # - name: format check
    #   run: yarn format --check
    - name: lint
      run: yarn lint
    - name: build
      run: yarn build
    - name: test
      run: yarn test
    - name: commitlint
      uses: wagoid/commitlint-github-action@v1.2.2
    - name: setting git values
      run: |
        git config --local user.email "cdaringe@cdaringe.com"
        git config --local user.name "cdaringe"
    - name: gh-pages
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.GH_TOKEN }}
        BASE_BRANCH: master
        BRANCH: gh-pages
        FOLDER: dist
        CLEAN: true
